baseURL = "https://yethon.github.io/south-end/"
languageCode = "en-us"
title = "South End Neighbors For Good"
theme = "terrassa"

publishDir = "docs"
staticDir = ["static"]

[params.hero]
    textColor = "white" # Empty for default color

[params.cta] # Call To Action
    show = true
    cta = "Get Involved"  # Text message of the CTA
    link = "volunteer" # Relative URL
